# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.cache/wt [current_project]
set_property parent.project_path F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/digital.coe
read_verilog -library xil_defaultlib {
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/ALU.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/Bdeal.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/BranchTest.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/Decode.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/EX.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/EX_MEM.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/Forwarding.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/ID.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/ID_EX.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/IF.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/IF_ID.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/InstructionROM.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/MEM_WB.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/MUX.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/PC.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/RAW_Registers.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/RBW_Registers.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/Risc5CPU.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/TMDSencode.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/add_sel.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/adder_32bits.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/src/riscv/adder_4bits.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/button_process_unit.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/syncGenarator.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/vga_data.v
  F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/PipelineCPUTest.v
}
read_ip -quiet F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
set_property used_in_implementation false [get_files -all f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc]
set_property used_in_implementation false [get_files -all f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc]
set_property used_in_implementation false [get_files -all f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc]

read_ip -quiet F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM.xci
set_property used_in_implementation false [get_files -all f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM_ooc.xdc]

read_ip -quiet F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM.xci
set_property used_in_implementation false [get_files -all f:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM_ooc.xdc]

read_edif F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/TMDSencode.edf
read_edif F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/button_process_unit.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/constrs_1/imports/PipelineCPU.srcs/VgaCPU.xdc
set_property used_in_implementation false [get_files F:/learning_data/computer_organization/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/constrs_1/imports/PipelineCPU.srcs/VgaCPU.xdc]


synth_design -top PipelineCPUTest -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PipelineCPUTest.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PipelineCPUTest_utilization_synth.rpt -pb PipelineCPUTest_utilization_synth.pb"
